CREATE DATABASE IF NOT EXISTS stock_portfolio;
USE stock_portfolio;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stocks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  symbol VARCHAR(50) NOT NULL,
  name VARCHAR(255),
  average_price DECIMAL(15, 2) DEFAULT 0.00,
  total_quantity INT DEFAULT 0,
  invested_amount DECIMAL(15, 2) DEFAULT 0.00,
  last_price DECIMAL(15, 2) DEFAULT 0.00,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY user_stock_unique (user_id, symbol)
);

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  symbol VARCHAR(50) NOT NULL,
  type ENUM('BUY', 'SELL') NOT NULL,
  price DECIMAL(15, 2) NOT NULL,
  quantity INT NOT NULL,
  realized_pl DECIMAL(15, 2) DEFAULT 0.00,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS portfolio_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  date DATETIME NOT NULL,
  total_invested DECIMAL(15, 2) DEFAULT 0.00,
  current_value DECIMAL(15, 2) DEFAULT 0.00,
  total_pl DECIMAL(15, 2) DEFAULT 0.00,
  day_change DECIMAL(15, 2) DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_date (user_id, date)
);
